# Generated by Django 4.2.3 on 2023-09-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0013_remove_itemadjustment_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('adjustment_type', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.chart_of_account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.company_details')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('adjustment_type', models.CharField(max_length=255)),
                ('quantity_available', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_quantity_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.adjustment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
