# Generated by Django 4.2.3 on 2023-09-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_inventory_adj_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='itemtable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
        migrations.AddField(
            model_name='itemadjustment',
            name='itemtable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
